### ISSUE TITLE
[contract] Verify Custom Types

### ISSUE THREAD

**Issue by scuellar** [GaloisInc/formal-verso#1]
The example contract for Custom Types is [described in the Soroban tutorial](https://developers.stellar.org/docs/smart-contracts/example-contracts/custom-types) and the code can be found [here](https://github.com/stellar/soroban-examples/tree/v20.0.0/custom_types).

We have a preliminary version of the verification [here](https://github.com/GaloisInc/formal-verso/blob/main/example-proofs/custom_types.saw), but relies on a temporary hack that we want to fix.

**Comment by sauclovian-g** [comment]
More accurately we have a working variant [here](https://github.com/GaloisInc/formal-verso/blob/main/example-proofs/custom_types2.saw) that ends up using vectors in the backend; the original requires handling map values, which we don't have support for yet.

**Comment by sauclovian-g** [comment]
The full custom_types example works as of commit 897c94cf3bc0eb5f1a0674c6a1c39cc05b607189.
